uint64 timestamp			# time since system start (microseconds)
uint8 alm_cell_ov
uint8 alm_cell_uv
uint8 alm_cell_ot
uint8 alm_cell_ut
uint8 alm_cell_lbk
uint8 alm_cell_tbk
uint8 alm_batt_dv
uint8 alm_batt_dt
uint8 alm_batt_ov
uint8 alm_batt_uv
uint8 alm_batt_oc
uint8 alm_batt_uc
uint8 alm_chrg_ocs
uint8 alm_dsch_ocs
uint8 alm_chrg_oct
uint8 alm_dsch_oct
uint8 alm_bsu_offline
uint8 alm_bsu_fault
uint8 alm_leak_oc
uint8 alm_prechrg_fail
uint8 alm_aux_fail
uint8 alm_bmu_fail
uint8 alm_vcu_offline
uint8 alm_hvrel_fail
uint8 alm_hall_break

