#!/bin/sh
#
# @name DB Multirotor with tilt
#
# @class Copter
# @type Tricopter Y+
#
# @output Motor1 motor 1
# @output Motor2 motor 2
# @output Motor3 motor 3
# @output Servo1 yaw servo
# @output Servo2 yaw servo
#
# @board bitcraze_crazyflie exclude
# @board px4_fmu-v2 exclude
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 15

param set-default CA_AIRFRAME 8
# Tricopter
param set-default CA_ROTOR0_PX 0.383
param set-default CA_ROTOR0_PY -0.898
param set-default CA_ROTOR0_TILT 1

param set-default CA_ROTOR1_PX 0.383
param set-default CA_ROTOR1_PY 0.898
param set-default CA_ROTOR1_TILT 2

param set-default CA_ROTOR2_PX -0.825
param set-default CA_ROTOR2_PY 0

param set-default CA_ROTOR_COUNT 3
param set-default CA_SV_TL0_MAXA 45
param set-default CA_SV_TL0_MINA -45
param set-default CA_SV_TL0_TD 90
param set-default CA_SV_TL1_MAXA 45
param set-default CA_SV_TL1_MINA -45
param set-default CA_SV_TL1_TD 90
param set-default CA_SV_TL_COUNT 2

# DB param
# TELEM used GPS2
param set-default MAV_0_CONFIG 202
param set-default SER_GPS2_BAUD 57600

# C-RTK 2HP
param set-default SER_GPS1_BAUD 230400

# NMEA
param set-default GPS_1_PROTOCOL 6

